### ISSUE TITLE
Design API

### ISSUE THREAD

**Issue by dmdwns2** [a01575dc-b401-4506-8753-7d523b558dfa/membership-service#2]
<img width="1422" alt="스크린샷 2023-07-02 오후 4 58 01" src="https://github.com/a01575dc-b401-4506-8753-7d523b558dfa/membership-service/assets/105894868/a3eb67f6-67e7-4751-affd-45ef1aa73d0c">

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
# 진행 순서(?)

- [x] 설계 논의
- [ ] OpenAPI 작성
    - [이걸](https://editor.swagger.io/) 활용하면 작성하기 편할 것 같다. 
- [ ] Swagger 연동
    - 컨트롤러를 스캔할 필요가 없다.
    - 위에서 작성한 명세를 시각화한다.

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
# OpenAPI 를 직접 작성하면 좋은 점(?)

- 컨트롤러에 annotation 이 떡칠되는 사태를 피할 수 있다.
    - 아무래도 이게 가장 큰 이점인 것 같다. 
- annotation 의 표현력에 제한받지 않는다.
    - 조금만 복잡해지면, 보기 힘들어진다.
    - OpenAPI 표준을 전부 지원하는게 아니다.

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
# Path

- 멤버십 발급
    - `POST /api/v1/memberships`
- 포인트 적립
    - `POST /api/v1/memberships/history`
- 포인트 사용
    - `POST /api/v1/memberships/history`
- 이력 조회
    - `GET /api/v1/memberships/history`

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
PATH 이외로 정보가 들어오는 것은, 다음과 같이 처리한다.
- `GET` 의 경우는 query parameter 를 사용
- `POST` 의 경우는 form + json 을 사용

당초 계획했던 OpenAPI 적용은, 이슈의 성격에 맞게 일단 여기서는 제외한다.
