### ISSUE TITLE
Creating an entity

### ISSUE THREAD

**Issue by dmdwns2** [a01575dc-b401-4506-8753-7d523b558dfa/membership-service#4]
![234605437-9110a30c-2267-4120-be1e-7290793e7f40](https://github.com/a01575dc-b401-4506-8753-7d523b558dfa/membership-service/assets/105894868/f13c776a-75a4-4eef-bc61-7e0f536869e3)

위 모델을 토대로 엔티티 작성하기

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
# Layered Architecture

- entity 를 infra 에 정의하고, service 에서 이걸 가져다 쓰는 방식이다.
    - entity 에 변경이 있다면, 여기에 의존하고 있는 service 가 영향을 받는다.
- domain entity <> jpa entity 를 분리해서 정의하면, 의존 관계를 역전시킬 수도 있다.
    - service 에서는 domain entity 기준으로 interface 를 정의한다.
    - infra 에서 이 interface 를 구현하고, 내부적으로는 jpa entity 로 변환한다.
    - [Get Your Hands Dirty on Clean Architecture](https://product.kyobobook.co.kr/detail/S000003533783) 라는 책에서 이 방식을 짧게 언급한 적이 있다.
        - 번역본은 여기 https://product.kyobobook.co.kr/detail/S000001766486
    - 그런데, 이렇게까지 해야 하는가에 대한 의견은 사람마다 다르므로 layered 가 반드시 나쁜 것은 아닐듯
        - 어떤 사람은 layered 가 아니라, clean architecture 를 사용해야 한다고 생각할 수 있다.
        - 어떤 사람은 layered 를 사용하지만, 위에서 언급한 의존 관계 역전으로 충분하다고 생각할 수도 있다.
        - 어떤 사람은 layered 를 잘 쓰면 상관 없다고 생각할 수도 있다.

```
.
├── infra
│   └── entity
│       ├── SomeEntity.java
│       └── SomeRepository.java
├── presentation
└── service
```

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
# Hexagonal Architecture

- 서비스에서 의존하는 모든 것이 interface 로 정의되는 극단적인 사례
    - 외부 의존은 input + output port 두 개의 분류를 갖는 port 로 정의해둔다.
    - 패키지 내부에서 비즈니스 로직은 모두 이것을 기준으로 작성한다.
    - 모두 interface 에 의존하므로, stub/mocking 테스트가 간편하다고 느낄 수도 있다.
        - stub/mocking 해야하는 대상 메소드가 한정돼있다는 의미다.
        - jpa repository 를 예로 든다면,
            - 메소드가 많기 때문에 stub 하는 것은 상상할 수 없고,
            - mocking 을 한다고 하더라도 pure java 로는 어렵다. (i.e., mockito 같은 것을 써야함.)
- entity 를 이것으로 정의한다면,
    - domain package 에 domain entity 를 정의한다.
    - application package 의 output port 에 사용할 interface 로 모두 정의한다.
        - update user
        - find user
        - delete user
        - ...
    - adapter package 에서 위 interface 를 만족하도록 jpa entity + repository 를 생성한다.
- 예시
    - https://github.com/thombergs/buckpal

**Comment by a01575dc-b401-4506-8753-7d523b558dfa** [comment]
대충 정리해봤는데 원하는 방향으로 해보면 될듯 🤔
